
const d = new Diagram();
const llm = d.addEllipse("LLM\n(Claude, etc.)", { row: 0, col: 2, color: "ai" });
const mcp = d.addBox("MCP Server\n(index.ts)", { row: 1, col: 2, color: "orchestration" });
const exec = d.addBox("Executor\n(new Function)", { row: 2, col: 2, color: "backend" });
const sdk = d.addBox("Diagram SDK\n(sdk.ts)", { row: 3, col: 2, color: "backend" });
const graphviz = d.addBox("Graphviz WASM\n(layout.ts)", { row: 4, col: 1, color: "database" });
const zigwasm = d.addBox("Zig WASM\n(validate)", { row: 4, col: 2, color: "storage" });
const upload = d.addBox("Upload\n(upload.ts)", { row: 4, col: 0, color: "external" });
const imgExport = d.addBox("Image Export\n(png.ts)", { row: 4, col: 3, color: "cache" });
const urlOut = d.addBox("excalidraw.com\nURL", { row: 5, col: 0, color: "frontend" });
const fileOut = d.addBox(".excalidraw\nfile", { row: 5, col: 1, color: "frontend" });
const sidecar = d.addBox(".drawmode.ts\nsidecar", { row: 5, col: 2, color: "frontend" });
const pngOut = d.addBox("PNG / SVG\nfile", { row: 5, col: 3, color: "frontend" });
d.connect(llm, mcp, "draw tool");
d.connect(mcp, exec, "code");
d.connect(exec, sdk, "Diagram API");
d.connect(sdk, graphviz, "layout");
d.connect(sdk, zigwasm, "validate");
d.connect(sdk, upload, "encrypt + POST");
d.connect(sdk, imgExport, "elements");
d.connect(sdk, fileOut, "write JSON");
d.connect(sdk, sidecar, "write source");
d.connect(upload, urlOut, "shareable link");
d.connect(imgExport, pngOut, "puppeteer render");
d.connect(graphviz, sdk, "positions", { style: "dashed" });
d.addGroup("Core", [exec, sdk]);
d.addGroup("Layout & Export", [graphviz, zigwasm, upload, imgExport]);
d.addGroup("Outputs", [urlOut, fileOut, sidecar, pngOut]);
return d.render({ format: ["excalidraw", "png", "svg"], path: "architecture.excalidraw" });
