name = "drawmode"
main = "index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "unsafe_eval"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[build]
command = "cd .. && pnpm build"
watch_dir = "../src"
