name = "drawmode"
main = "index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "unsafe_eval"]

[browser]
binding = "MYBROWSER"

[wasm_modules]
DRAWMODE_WASM = "../wasm/zig-out/bin/drawmode.wasm"

[build]
command = "cd .. && pnpm build"
